name: Deploy First Surge website

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Setup Node.js Environment
      uses: actions/setup-node@v2-beta
      with:
        node-version: 12

    - name: Installing Surge
      run: npm install --global surge
      
      name: deploying using surge
      
      run: surge ./ FirstBootcampproject.surge.sh --token $ {{secrets.First_Surge_token}}
